# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mateimirica/Desktop/pystreed

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mateimirica/Desktop/pystreed

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.29.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mateimirica/Desktop/pystreed/CMakeFiles /Users/mateimirica/Desktop/pystreed//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mateimirica/Desktop/pystreed/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named STREEDLib

# Build rule for target.
STREEDLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 STREEDLib
.PHONY : STREEDLib

# fast build rule for target.
STREEDLib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/build
.PHONY : STREEDLib/fast

#=============================================================================
# Target rules for targets named STREED

# Build rule for target.
STREED: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 STREED
.PHONY : STREED

# fast build rule for target.
STREED/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREED.dir/build.make CMakeFiles/STREED.dir/build
.PHONY : STREED/fast

#=============================================================================
# Target rules for targets named CorrectSolutionTest

# Build rule for target.
CorrectSolutionTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CorrectSolutionTest
.PHONY : CorrectSolutionTest

# fast build rule for target.
CorrectSolutionTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CorrectSolutionTest.dir/build.make CMakeFiles/CorrectSolutionTest.dir/build
.PHONY : CorrectSolutionTest/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREED.dir/build.make CMakeFiles/STREED.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREED.dir/build.make CMakeFiles/STREED.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREED.dir/build.make CMakeFiles/STREED.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model/branch.o: src/model/branch.cpp.o
.PHONY : src/model/branch.o

# target to build an object file
src/model/branch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/model/branch.cpp.o
.PHONY : src/model/branch.cpp.o

src/model/branch.i: src/model/branch.cpp.i
.PHONY : src/model/branch.i

# target to preprocess a source file
src/model/branch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/model/branch.cpp.i
.PHONY : src/model/branch.cpp.i

src/model/branch.s: src/model/branch.cpp.s
.PHONY : src/model/branch.s

# target to generate assembly for a file
src/model/branch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/model/branch.cpp.s
.PHONY : src/model/branch.cpp.s

src/model/data.o: src/model/data.cpp.o
.PHONY : src/model/data.o

# target to build an object file
src/model/data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/model/data.cpp.o
.PHONY : src/model/data.cpp.o

src/model/data.i: src/model/data.cpp.i
.PHONY : src/model/data.i

# target to preprocess a source file
src/model/data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/model/data.cpp.i
.PHONY : src/model/data.cpp.i

src/model/data.s: src/model/data.cpp.s
.PHONY : src/model/data.s

# target to generate assembly for a file
src/model/data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/model/data.cpp.s
.PHONY : src/model/data.cpp.s

src/model/feature_vector.o: src/model/feature_vector.cpp.o
.PHONY : src/model/feature_vector.o

# target to build an object file
src/model/feature_vector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/model/feature_vector.cpp.o
.PHONY : src/model/feature_vector.cpp.o

src/model/feature_vector.i: src/model/feature_vector.cpp.i
.PHONY : src/model/feature_vector.i

# target to preprocess a source file
src/model/feature_vector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/model/feature_vector.cpp.i
.PHONY : src/model/feature_vector.cpp.i

src/model/feature_vector.s: src/model/feature_vector.cpp.s
.PHONY : src/model/feature_vector.s

# target to generate assembly for a file
src/model/feature_vector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/model/feature_vector.cpp.s
.PHONY : src/model/feature_vector.cpp.s

src/solver/branch_cache.o: src/solver/branch_cache.cpp.o
.PHONY : src/solver/branch_cache.o

# target to build an object file
src/solver/branch_cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/branch_cache.cpp.o
.PHONY : src/solver/branch_cache.cpp.o

src/solver/branch_cache.i: src/solver/branch_cache.cpp.i
.PHONY : src/solver/branch_cache.i

# target to preprocess a source file
src/solver/branch_cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/branch_cache.cpp.i
.PHONY : src/solver/branch_cache.cpp.i

src/solver/branch_cache.s: src/solver/branch_cache.cpp.s
.PHONY : src/solver/branch_cache.s

# target to generate assembly for a file
src/solver/branch_cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/branch_cache.cpp.s
.PHONY : src/solver/branch_cache.cpp.s

src/solver/cache.o: src/solver/cache.cpp.o
.PHONY : src/solver/cache.o

# target to build an object file
src/solver/cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/cache.cpp.o
.PHONY : src/solver/cache.cpp.o

src/solver/cache.i: src/solver/cache.cpp.i
.PHONY : src/solver/cache.i

# target to preprocess a source file
src/solver/cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/cache.cpp.i
.PHONY : src/solver/cache.cpp.i

src/solver/cache.s: src/solver/cache.cpp.s
.PHONY : src/solver/cache.s

# target to generate assembly for a file
src/solver/cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/cache.cpp.s
.PHONY : src/solver/cache.cpp.s

src/solver/cost_combiner.o: src/solver/cost_combiner.cpp.o
.PHONY : src/solver/cost_combiner.o

# target to build an object file
src/solver/cost_combiner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/cost_combiner.cpp.o
.PHONY : src/solver/cost_combiner.cpp.o

src/solver/cost_combiner.i: src/solver/cost_combiner.cpp.i
.PHONY : src/solver/cost_combiner.i

# target to preprocess a source file
src/solver/cost_combiner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/cost_combiner.cpp.i
.PHONY : src/solver/cost_combiner.cpp.i

src/solver/cost_combiner.s: src/solver/cost_combiner.cpp.s
.PHONY : src/solver/cost_combiner.s

# target to generate assembly for a file
src/solver/cost_combiner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/cost_combiner.cpp.s
.PHONY : src/solver/cost_combiner.cpp.s

src/solver/cost_storage.o: src/solver/cost_storage.cpp.o
.PHONY : src/solver/cost_storage.o

# target to build an object file
src/solver/cost_storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/cost_storage.cpp.o
.PHONY : src/solver/cost_storage.cpp.o

src/solver/cost_storage.i: src/solver/cost_storage.cpp.i
.PHONY : src/solver/cost_storage.i

# target to preprocess a source file
src/solver/cost_storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/cost_storage.cpp.i
.PHONY : src/solver/cost_storage.cpp.i

src/solver/cost_storage.s: src/solver/cost_storage.cpp.s
.PHONY : src/solver/cost_storage.s

# target to generate assembly for a file
src/solver/cost_storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/cost_storage.cpp.s
.PHONY : src/solver/cost_storage.cpp.s

src/solver/counter.o: src/solver/counter.cpp.o
.PHONY : src/solver/counter.o

# target to build an object file
src/solver/counter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/counter.cpp.o
.PHONY : src/solver/counter.cpp.o

src/solver/counter.i: src/solver/counter.cpp.i
.PHONY : src/solver/counter.i

# target to preprocess a source file
src/solver/counter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/counter.cpp.i
.PHONY : src/solver/counter.cpp.i

src/solver/counter.s: src/solver/counter.cpp.s
.PHONY : src/solver/counter.s

# target to generate assembly for a file
src/solver/counter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/counter.cpp.s
.PHONY : src/solver/counter.cpp.s

src/solver/data_splitter.o: src/solver/data_splitter.cpp.o
.PHONY : src/solver/data_splitter.o

# target to build an object file
src/solver/data_splitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/data_splitter.cpp.o
.PHONY : src/solver/data_splitter.cpp.o

src/solver/data_splitter.i: src/solver/data_splitter.cpp.i
.PHONY : src/solver/data_splitter.i

# target to preprocess a source file
src/solver/data_splitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/data_splitter.cpp.i
.PHONY : src/solver/data_splitter.cpp.i

src/solver/data_splitter.s: src/solver/data_splitter.cpp.s
.PHONY : src/solver/data_splitter.s

# target to generate assembly for a file
src/solver/data_splitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/data_splitter.cpp.s
.PHONY : src/solver/data_splitter.cpp.s

src/solver/dataset_cache.o: src/solver/dataset_cache.cpp.o
.PHONY : src/solver/dataset_cache.o

# target to build an object file
src/solver/dataset_cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/dataset_cache.cpp.o
.PHONY : src/solver/dataset_cache.cpp.o

src/solver/dataset_cache.i: src/solver/dataset_cache.cpp.i
.PHONY : src/solver/dataset_cache.i

# target to preprocess a source file
src/solver/dataset_cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/dataset_cache.cpp.i
.PHONY : src/solver/dataset_cache.cpp.i

src/solver/dataset_cache.s: src/solver/dataset_cache.cpp.s
.PHONY : src/solver/dataset_cache.s

# target to generate assembly for a file
src/solver/dataset_cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/dataset_cache.cpp.s
.PHONY : src/solver/dataset_cache.cpp.s

src/solver/define_parameters.o: src/solver/define_parameters.cpp.o
.PHONY : src/solver/define_parameters.o

# target to build an object file
src/solver/define_parameters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/define_parameters.cpp.o
.PHONY : src/solver/define_parameters.cpp.o

src/solver/define_parameters.i: src/solver/define_parameters.cpp.i
.PHONY : src/solver/define_parameters.i

# target to preprocess a source file
src/solver/define_parameters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/define_parameters.cpp.i
.PHONY : src/solver/define_parameters.cpp.i

src/solver/define_parameters.s: src/solver/define_parameters.cpp.s
.PHONY : src/solver/define_parameters.s

# target to generate assembly for a file
src/solver/define_parameters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/define_parameters.cpp.s
.PHONY : src/solver/define_parameters.cpp.s

src/solver/difference_computer.o: src/solver/difference_computer.cpp.o
.PHONY : src/solver/difference_computer.o

# target to build an object file
src/solver/difference_computer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/difference_computer.cpp.o
.PHONY : src/solver/difference_computer.cpp.o

src/solver/difference_computer.i: src/solver/difference_computer.cpp.i
.PHONY : src/solver/difference_computer.i

# target to preprocess a source file
src/solver/difference_computer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/difference_computer.cpp.i
.PHONY : src/solver/difference_computer.cpp.i

src/solver/difference_computer.s: src/solver/difference_computer.cpp.s
.PHONY : src/solver/difference_computer.s

# target to generate assembly for a file
src/solver/difference_computer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/difference_computer.cpp.s
.PHONY : src/solver/difference_computer.cpp.s

src/solver/feature_selector_gini.o: src/solver/feature_selector_gini.cpp.o
.PHONY : src/solver/feature_selector_gini.o

# target to build an object file
src/solver/feature_selector_gini.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/feature_selector_gini.cpp.o
.PHONY : src/solver/feature_selector_gini.cpp.o

src/solver/feature_selector_gini.i: src/solver/feature_selector_gini.cpp.i
.PHONY : src/solver/feature_selector_gini.i

# target to preprocess a source file
src/solver/feature_selector_gini.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/feature_selector_gini.cpp.i
.PHONY : src/solver/feature_selector_gini.cpp.i

src/solver/feature_selector_gini.s: src/solver/feature_selector_gini.cpp.s
.PHONY : src/solver/feature_selector_gini.s

# target to generate assembly for a file
src/solver/feature_selector_gini.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/feature_selector_gini.cpp.s
.PHONY : src/solver/feature_selector_gini.cpp.s

src/solver/result.o: src/solver/result.cpp.o
.PHONY : src/solver/result.o

# target to build an object file
src/solver/result.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/result.cpp.o
.PHONY : src/solver/result.cpp.o

src/solver/result.i: src/solver/result.cpp.i
.PHONY : src/solver/result.i

# target to preprocess a source file
src/solver/result.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/result.cpp.i
.PHONY : src/solver/result.cpp.i

src/solver/result.s: src/solver/result.cpp.s
.PHONY : src/solver/result.s

# target to generate assembly for a file
src/solver/result.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/result.cpp.s
.PHONY : src/solver/result.cpp.s

src/solver/similarity_lowerbound.o: src/solver/similarity_lowerbound.cpp.o
.PHONY : src/solver/similarity_lowerbound.o

# target to build an object file
src/solver/similarity_lowerbound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/similarity_lowerbound.cpp.o
.PHONY : src/solver/similarity_lowerbound.cpp.o

src/solver/similarity_lowerbound.i: src/solver/similarity_lowerbound.cpp.i
.PHONY : src/solver/similarity_lowerbound.i

# target to preprocess a source file
src/solver/similarity_lowerbound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/similarity_lowerbound.cpp.i
.PHONY : src/solver/similarity_lowerbound.cpp.i

src/solver/similarity_lowerbound.s: src/solver/similarity_lowerbound.cpp.s
.PHONY : src/solver/similarity_lowerbound.s

# target to generate assembly for a file
src/solver/similarity_lowerbound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/similarity_lowerbound.cpp.s
.PHONY : src/solver/similarity_lowerbound.cpp.s

src/solver/solver.o: src/solver/solver.cpp.o
.PHONY : src/solver/solver.o

# target to build an object file
src/solver/solver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/solver.cpp.o
.PHONY : src/solver/solver.cpp.o

src/solver/solver.i: src/solver/solver.cpp.i
.PHONY : src/solver/solver.i

# target to preprocess a source file
src/solver/solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/solver.cpp.i
.PHONY : src/solver/solver.cpp.i

src/solver/solver.s: src/solver/solver.cpp.s
.PHONY : src/solver/solver.s

# target to generate assembly for a file
src/solver/solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/solver.cpp.s
.PHONY : src/solver/solver.cpp.s

src/solver/terminal_solver.o: src/solver/terminal_solver.cpp.o
.PHONY : src/solver/terminal_solver.o

# target to build an object file
src/solver/terminal_solver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/terminal_solver.cpp.o
.PHONY : src/solver/terminal_solver.cpp.o

src/solver/terminal_solver.i: src/solver/terminal_solver.cpp.i
.PHONY : src/solver/terminal_solver.i

# target to preprocess a source file
src/solver/terminal_solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/terminal_solver.cpp.i
.PHONY : src/solver/terminal_solver.cpp.i

src/solver/terminal_solver.s: src/solver/terminal_solver.cpp.s
.PHONY : src/solver/terminal_solver.s

# target to generate assembly for a file
src/solver/terminal_solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/solver/terminal_solver.cpp.s
.PHONY : src/solver/terminal_solver.cpp.s

src/tasks/accuracy/accuracy.o: src/tasks/accuracy/accuracy.cpp.o
.PHONY : src/tasks/accuracy/accuracy.o

# target to build an object file
src/tasks/accuracy/accuracy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/accuracy/accuracy.cpp.o
.PHONY : src/tasks/accuracy/accuracy.cpp.o

src/tasks/accuracy/accuracy.i: src/tasks/accuracy/accuracy.cpp.i
.PHONY : src/tasks/accuracy/accuracy.i

# target to preprocess a source file
src/tasks/accuracy/accuracy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/accuracy/accuracy.cpp.i
.PHONY : src/tasks/accuracy/accuracy.cpp.i

src/tasks/accuracy/accuracy.s: src/tasks/accuracy/accuracy.cpp.s
.PHONY : src/tasks/accuracy/accuracy.s

# target to generate assembly for a file
src/tasks/accuracy/accuracy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/accuracy/accuracy.cpp.s
.PHONY : src/tasks/accuracy/accuracy.cpp.s

src/tasks/accuracy/cost_complex_accuracy.o: src/tasks/accuracy/cost_complex_accuracy.cpp.o
.PHONY : src/tasks/accuracy/cost_complex_accuracy.o

# target to build an object file
src/tasks/accuracy/cost_complex_accuracy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/accuracy/cost_complex_accuracy.cpp.o
.PHONY : src/tasks/accuracy/cost_complex_accuracy.cpp.o

src/tasks/accuracy/cost_complex_accuracy.i: src/tasks/accuracy/cost_complex_accuracy.cpp.i
.PHONY : src/tasks/accuracy/cost_complex_accuracy.i

# target to preprocess a source file
src/tasks/accuracy/cost_complex_accuracy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/accuracy/cost_complex_accuracy.cpp.i
.PHONY : src/tasks/accuracy/cost_complex_accuracy.cpp.i

src/tasks/accuracy/cost_complex_accuracy.s: src/tasks/accuracy/cost_complex_accuracy.cpp.s
.PHONY : src/tasks/accuracy/cost_complex_accuracy.s

# target to generate assembly for a file
src/tasks/accuracy/cost_complex_accuracy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/accuracy/cost_complex_accuracy.cpp.s
.PHONY : src/tasks/accuracy/cost_complex_accuracy.cpp.s

src/tasks/cost_sensitive.o: src/tasks/cost_sensitive.cpp.o
.PHONY : src/tasks/cost_sensitive.o

# target to build an object file
src/tasks/cost_sensitive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/cost_sensitive.cpp.o
.PHONY : src/tasks/cost_sensitive.cpp.o

src/tasks/cost_sensitive.i: src/tasks/cost_sensitive.cpp.i
.PHONY : src/tasks/cost_sensitive.i

# target to preprocess a source file
src/tasks/cost_sensitive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/cost_sensitive.cpp.i
.PHONY : src/tasks/cost_sensitive.cpp.i

src/tasks/cost_sensitive.s: src/tasks/cost_sensitive.cpp.s
.PHONY : src/tasks/cost_sensitive.s

# target to generate assembly for a file
src/tasks/cost_sensitive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/cost_sensitive.cpp.s
.PHONY : src/tasks/cost_sensitive.cpp.s

src/tasks/cox_survival_analysis.o: src/tasks/cox_survival_analysis.cpp.o
.PHONY : src/tasks/cox_survival_analysis.o

# target to build an object file
src/tasks/cox_survival_analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/cox_survival_analysis.cpp.o
.PHONY : src/tasks/cox_survival_analysis.cpp.o

src/tasks/cox_survival_analysis.i: src/tasks/cox_survival_analysis.cpp.i
.PHONY : src/tasks/cox_survival_analysis.i

# target to preprocess a source file
src/tasks/cox_survival_analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/cox_survival_analysis.cpp.i
.PHONY : src/tasks/cox_survival_analysis.cpp.i

src/tasks/cox_survival_analysis.s: src/tasks/cox_survival_analysis.cpp.s
.PHONY : src/tasks/cox_survival_analysis.s

# target to generate assembly for a file
src/tasks/cox_survival_analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/cox_survival_analysis.cpp.s
.PHONY : src/tasks/cox_survival_analysis.cpp.s

src/tasks/eq_opp.o: src/tasks/eq_opp.cpp.o
.PHONY : src/tasks/eq_opp.o

# target to build an object file
src/tasks/eq_opp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/eq_opp.cpp.o
.PHONY : src/tasks/eq_opp.cpp.o

src/tasks/eq_opp.i: src/tasks/eq_opp.cpp.i
.PHONY : src/tasks/eq_opp.i

# target to preprocess a source file
src/tasks/eq_opp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/eq_opp.cpp.i
.PHONY : src/tasks/eq_opp.cpp.i

src/tasks/eq_opp.s: src/tasks/eq_opp.cpp.s
.PHONY : src/tasks/eq_opp.s

# target to generate assembly for a file
src/tasks/eq_opp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/eq_opp.cpp.s
.PHONY : src/tasks/eq_opp.cpp.s

src/tasks/f1score.o: src/tasks/f1score.cpp.o
.PHONY : src/tasks/f1score.o

# target to build an object file
src/tasks/f1score.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/f1score.cpp.o
.PHONY : src/tasks/f1score.cpp.o

src/tasks/f1score.i: src/tasks/f1score.cpp.i
.PHONY : src/tasks/f1score.i

# target to preprocess a source file
src/tasks/f1score.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/f1score.cpp.i
.PHONY : src/tasks/f1score.cpp.i

src/tasks/f1score.s: src/tasks/f1score.cpp.s
.PHONY : src/tasks/f1score.s

# target to generate assembly for a file
src/tasks/f1score.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/f1score.cpp.s
.PHONY : src/tasks/f1score.cpp.s

src/tasks/group_fairness.o: src/tasks/group_fairness.cpp.o
.PHONY : src/tasks/group_fairness.o

# target to build an object file
src/tasks/group_fairness.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/group_fairness.cpp.o
.PHONY : src/tasks/group_fairness.cpp.o

src/tasks/group_fairness.i: src/tasks/group_fairness.cpp.i
.PHONY : src/tasks/group_fairness.i

# target to preprocess a source file
src/tasks/group_fairness.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/group_fairness.cpp.i
.PHONY : src/tasks/group_fairness.cpp.i

src/tasks/group_fairness.s: src/tasks/group_fairness.cpp.s
.PHONY : src/tasks/group_fairness.s

# target to generate assembly for a file
src/tasks/group_fairness.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/group_fairness.cpp.s
.PHONY : src/tasks/group_fairness.cpp.s

src/tasks/instance_cost_sensitive.o: src/tasks/instance_cost_sensitive.cpp.o
.PHONY : src/tasks/instance_cost_sensitive.o

# target to build an object file
src/tasks/instance_cost_sensitive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/instance_cost_sensitive.cpp.o
.PHONY : src/tasks/instance_cost_sensitive.cpp.o

src/tasks/instance_cost_sensitive.i: src/tasks/instance_cost_sensitive.cpp.i
.PHONY : src/tasks/instance_cost_sensitive.i

# target to preprocess a source file
src/tasks/instance_cost_sensitive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/instance_cost_sensitive.cpp.i
.PHONY : src/tasks/instance_cost_sensitive.cpp.i

src/tasks/instance_cost_sensitive.s: src/tasks/instance_cost_sensitive.cpp.s
.PHONY : src/tasks/instance_cost_sensitive.s

# target to generate assembly for a file
src/tasks/instance_cost_sensitive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/instance_cost_sensitive.cpp.s
.PHONY : src/tasks/instance_cost_sensitive.cpp.s

src/tasks/optimization_task.o: src/tasks/optimization_task.cpp.o
.PHONY : src/tasks/optimization_task.o

# target to build an object file
src/tasks/optimization_task.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/optimization_task.cpp.o
.PHONY : src/tasks/optimization_task.cpp.o

src/tasks/optimization_task.i: src/tasks/optimization_task.cpp.i
.PHONY : src/tasks/optimization_task.i

# target to preprocess a source file
src/tasks/optimization_task.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/optimization_task.cpp.i
.PHONY : src/tasks/optimization_task.cpp.i

src/tasks/optimization_task.s: src/tasks/optimization_task.cpp.s
.PHONY : src/tasks/optimization_task.s

# target to generate assembly for a file
src/tasks/optimization_task.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/optimization_task.cpp.s
.PHONY : src/tasks/optimization_task.cpp.s

src/tasks/prescriptive_policy.o: src/tasks/prescriptive_policy.cpp.o
.PHONY : src/tasks/prescriptive_policy.o

# target to build an object file
src/tasks/prescriptive_policy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/prescriptive_policy.cpp.o
.PHONY : src/tasks/prescriptive_policy.cpp.o

src/tasks/prescriptive_policy.i: src/tasks/prescriptive_policy.cpp.i
.PHONY : src/tasks/prescriptive_policy.i

# target to preprocess a source file
src/tasks/prescriptive_policy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/prescriptive_policy.cpp.i
.PHONY : src/tasks/prescriptive_policy.cpp.i

src/tasks/prescriptive_policy.s: src/tasks/prescriptive_policy.cpp.s
.PHONY : src/tasks/prescriptive_policy.s

# target to generate assembly for a file
src/tasks/prescriptive_policy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/prescriptive_policy.cpp.s
.PHONY : src/tasks/prescriptive_policy.cpp.s

src/tasks/survival_analysis.o: src/tasks/survival_analysis.cpp.o
.PHONY : src/tasks/survival_analysis.o

# target to build an object file
src/tasks/survival_analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/survival_analysis.cpp.o
.PHONY : src/tasks/survival_analysis.cpp.o

src/tasks/survival_analysis.i: src/tasks/survival_analysis.cpp.i
.PHONY : src/tasks/survival_analysis.i

# target to preprocess a source file
src/tasks/survival_analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/survival_analysis.cpp.i
.PHONY : src/tasks/survival_analysis.cpp.i

src/tasks/survival_analysis.s: src/tasks/survival_analysis.cpp.s
.PHONY : src/tasks/survival_analysis.s

# target to generate assembly for a file
src/tasks/survival_analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/tasks/survival_analysis.cpp.s
.PHONY : src/tasks/survival_analysis.cpp.s

src/utils/file_reader.o: src/utils/file_reader.cpp.o
.PHONY : src/utils/file_reader.o

# target to build an object file
src/utils/file_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/utils/file_reader.cpp.o
.PHONY : src/utils/file_reader.cpp.o

src/utils/file_reader.i: src/utils/file_reader.cpp.i
.PHONY : src/utils/file_reader.i

# target to preprocess a source file
src/utils/file_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/utils/file_reader.cpp.i
.PHONY : src/utils/file_reader.cpp.i

src/utils/file_reader.s: src/utils/file_reader.cpp.s
.PHONY : src/utils/file_reader.s

# target to generate assembly for a file
src/utils/file_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/utils/file_reader.cpp.s
.PHONY : src/utils/file_reader.cpp.s

src/utils/key_value_heap.o: src/utils/key_value_heap.cpp.o
.PHONY : src/utils/key_value_heap.o

# target to build an object file
src/utils/key_value_heap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/utils/key_value_heap.cpp.o
.PHONY : src/utils/key_value_heap.cpp.o

src/utils/key_value_heap.i: src/utils/key_value_heap.cpp.i
.PHONY : src/utils/key_value_heap.i

# target to preprocess a source file
src/utils/key_value_heap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/utils/key_value_heap.cpp.i
.PHONY : src/utils/key_value_heap.cpp.i

src/utils/key_value_heap.s: src/utils/key_value_heap.cpp.s
.PHONY : src/utils/key_value_heap.s

# target to generate assembly for a file
src/utils/key_value_heap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/utils/key_value_heap.cpp.s
.PHONY : src/utils/key_value_heap.cpp.s

src/utils/parameter_handler.o: src/utils/parameter_handler.cpp.o
.PHONY : src/utils/parameter_handler.o

# target to build an object file
src/utils/parameter_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/utils/parameter_handler.cpp.o
.PHONY : src/utils/parameter_handler.cpp.o

src/utils/parameter_handler.i: src/utils/parameter_handler.cpp.i
.PHONY : src/utils/parameter_handler.i

# target to preprocess a source file
src/utils/parameter_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/utils/parameter_handler.cpp.i
.PHONY : src/utils/parameter_handler.cpp.i

src/utils/parameter_handler.s: src/utils/parameter_handler.cpp.s
.PHONY : src/utils/parameter_handler.s

# target to generate assembly for a file
src/utils/parameter_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STREEDLib.dir/build.make CMakeFiles/STREEDLib.dir/src/utils/parameter_handler.cpp.s
.PHONY : src/utils/parameter_handler.cpp.s

test/correct_solution_test.o: test/correct_solution_test.cpp.o
.PHONY : test/correct_solution_test.o

# target to build an object file
test/correct_solution_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CorrectSolutionTest.dir/build.make CMakeFiles/CorrectSolutionTest.dir/test/correct_solution_test.cpp.o
.PHONY : test/correct_solution_test.cpp.o

test/correct_solution_test.i: test/correct_solution_test.cpp.i
.PHONY : test/correct_solution_test.i

# target to preprocess a source file
test/correct_solution_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CorrectSolutionTest.dir/build.make CMakeFiles/CorrectSolutionTest.dir/test/correct_solution_test.cpp.i
.PHONY : test/correct_solution_test.cpp.i

test/correct_solution_test.s: test/correct_solution_test.cpp.s
.PHONY : test/correct_solution_test.s

# target to generate assembly for a file
test/correct_solution_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CorrectSolutionTest.dir/build.make CMakeFiles/CorrectSolutionTest.dir/test/correct_solution_test.cpp.s
.PHONY : test/correct_solution_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... CorrectSolutionTest"
	@echo "... STREED"
	@echo "... STREEDLib"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model/branch.o"
	@echo "... src/model/branch.i"
	@echo "... src/model/branch.s"
	@echo "... src/model/data.o"
	@echo "... src/model/data.i"
	@echo "... src/model/data.s"
	@echo "... src/model/feature_vector.o"
	@echo "... src/model/feature_vector.i"
	@echo "... src/model/feature_vector.s"
	@echo "... src/solver/branch_cache.o"
	@echo "... src/solver/branch_cache.i"
	@echo "... src/solver/branch_cache.s"
	@echo "... src/solver/cache.o"
	@echo "... src/solver/cache.i"
	@echo "... src/solver/cache.s"
	@echo "... src/solver/cost_combiner.o"
	@echo "... src/solver/cost_combiner.i"
	@echo "... src/solver/cost_combiner.s"
	@echo "... src/solver/cost_storage.o"
	@echo "... src/solver/cost_storage.i"
	@echo "... src/solver/cost_storage.s"
	@echo "... src/solver/counter.o"
	@echo "... src/solver/counter.i"
	@echo "... src/solver/counter.s"
	@echo "... src/solver/data_splitter.o"
	@echo "... src/solver/data_splitter.i"
	@echo "... src/solver/data_splitter.s"
	@echo "... src/solver/dataset_cache.o"
	@echo "... src/solver/dataset_cache.i"
	@echo "... src/solver/dataset_cache.s"
	@echo "... src/solver/define_parameters.o"
	@echo "... src/solver/define_parameters.i"
	@echo "... src/solver/define_parameters.s"
	@echo "... src/solver/difference_computer.o"
	@echo "... src/solver/difference_computer.i"
	@echo "... src/solver/difference_computer.s"
	@echo "... src/solver/feature_selector_gini.o"
	@echo "... src/solver/feature_selector_gini.i"
	@echo "... src/solver/feature_selector_gini.s"
	@echo "... src/solver/result.o"
	@echo "... src/solver/result.i"
	@echo "... src/solver/result.s"
	@echo "... src/solver/similarity_lowerbound.o"
	@echo "... src/solver/similarity_lowerbound.i"
	@echo "... src/solver/similarity_lowerbound.s"
	@echo "... src/solver/solver.o"
	@echo "... src/solver/solver.i"
	@echo "... src/solver/solver.s"
	@echo "... src/solver/terminal_solver.o"
	@echo "... src/solver/terminal_solver.i"
	@echo "... src/solver/terminal_solver.s"
	@echo "... src/tasks/accuracy/accuracy.o"
	@echo "... src/tasks/accuracy/accuracy.i"
	@echo "... src/tasks/accuracy/accuracy.s"
	@echo "... src/tasks/accuracy/cost_complex_accuracy.o"
	@echo "... src/tasks/accuracy/cost_complex_accuracy.i"
	@echo "... src/tasks/accuracy/cost_complex_accuracy.s"
	@echo "... src/tasks/cost_sensitive.o"
	@echo "... src/tasks/cost_sensitive.i"
	@echo "... src/tasks/cost_sensitive.s"
	@echo "... src/tasks/cox_survival_analysis.o"
	@echo "... src/tasks/cox_survival_analysis.i"
	@echo "... src/tasks/cox_survival_analysis.s"
	@echo "... src/tasks/eq_opp.o"
	@echo "... src/tasks/eq_opp.i"
	@echo "... src/tasks/eq_opp.s"
	@echo "... src/tasks/f1score.o"
	@echo "... src/tasks/f1score.i"
	@echo "... src/tasks/f1score.s"
	@echo "... src/tasks/group_fairness.o"
	@echo "... src/tasks/group_fairness.i"
	@echo "... src/tasks/group_fairness.s"
	@echo "... src/tasks/instance_cost_sensitive.o"
	@echo "... src/tasks/instance_cost_sensitive.i"
	@echo "... src/tasks/instance_cost_sensitive.s"
	@echo "... src/tasks/optimization_task.o"
	@echo "... src/tasks/optimization_task.i"
	@echo "... src/tasks/optimization_task.s"
	@echo "... src/tasks/prescriptive_policy.o"
	@echo "... src/tasks/prescriptive_policy.i"
	@echo "... src/tasks/prescriptive_policy.s"
	@echo "... src/tasks/survival_analysis.o"
	@echo "... src/tasks/survival_analysis.i"
	@echo "... src/tasks/survival_analysis.s"
	@echo "... src/utils/file_reader.o"
	@echo "... src/utils/file_reader.i"
	@echo "... src/utils/file_reader.s"
	@echo "... src/utils/key_value_heap.o"
	@echo "... src/utils/key_value_heap.i"
	@echo "... src/utils/key_value_heap.s"
	@echo "... src/utils/parameter_handler.o"
	@echo "... src/utils/parameter_handler.i"
	@echo "... src/utils/parameter_handler.s"
	@echo "... test/correct_solution_test.o"
	@echo "... test/correct_solution_test.i"
	@echo "... test/correct_solution_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

